ON_PYCHARM: "Empty"
WIDTH: 20
HEIGHT: 11
TOTAL_GENERATIONS: 5
DELAY_BETWEEN_GENERATIONS: 0.5
NUM_OF_PLANTS: 10
PLANTS_STEPS: 2
HERBIVORE_STEPS: 15
PREDATOR_STEPS: 10
TEMPLATE_PATTERN:
 - ["Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty"]
 - ["Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty"]
 - ["Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty"]
 - ["Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Basic", "Empty", "Basic", "Empty", "Basic", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty"]
 - ["Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Basic", "Empty", "Empty", "Empty", "Empty", "Empty", "Basic", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty"]
 - ["Empty", "Empty", "Empty", "Empty", "Empty", "Basic", "Empty", "Basic", "Empty", "Empty", "Empty", "Basic", "Empty", "Basic", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty"]
 - ["Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Basic", "Empty", "Empty", "Empty", "Empty", "Empty", "Basic", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty"]
 - ["Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Basic", "Empty", "Basic", "Empty", "Basic", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty"]
 - ["Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty"]
 - ["Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty"]
 - ["Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty"]