ON_PYCHARM: "Empty"
WIDTH: 20
HEIGHT: 11
TOTAL_GENERATIONS: 5
DELAY_BETWEEN_GENERATIONS: 0.5

NUM_OF_PLANTS: 10
PLANTS_STEPS: 2

HERBIVORE_STEPS: 15
HERBIVORE_SIGHT: 10

PREDATOR_STEPS: 10
PREDATOR_SIGHT: 10

TEMPLATE_PATTERN:
 - ["Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty"]
 - ["Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty"]
 - ["Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty"]
 - ["Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Basic", "Empty", "Herbivore", "Empty", "Basic", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty"]
 - ["Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Basic", "Empty", "Empty", "Empty", "Empty", "Empty", "Basic", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty"]
 - ["Empty", "Empty", "Empty", "Empty", "Empty", "Basic", "Empty", "Basic", "Empty", "Empty", "Empty", "Basic", "Empty", "Basic", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty"]
 - ["Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Basic", "Empty", "Empty", "Empty", "Empty", "Empty", "Basic", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty"]
 - ["Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Basic", "Empty", "Basic", "Empty", "Herbivore", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty"]
 - ["Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty"]
 - ["Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty"]
 - ["Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty", "Empty"]